name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout
    - name: Build the Docker image
      run: docker build . 
    steps:
    - uses: actions/checkout
    - name: Build the Docker image
      run: docker build .
